version: '3.8'
services:
  postgres:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_DB=katana
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '5432:5432'
  test-db:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_DB=katana
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '5433:5432'
